@baseUrl = http://localhost:3001/api
@userid = player1
@password = 12345678

###
# good login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "username": "{{userid}}",
    "password": "{{password}}"
}

###
# bad login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "userid": "{{userid}}",
    "password": "{{password}}1"
}

###
# check session
GET {{baseUrl}}/sessions/current

###
# log out
DELETE {{baseUrl}}/sessions/current

###
# get records
GET {{baseUrl}}/games/records

###
# get network
GET {{baseUrl}}/network

###
# get stations pairs
GET {{baseUrl}}/games/setup

###
# submit
POST {{baseUrl}}/games/submit
content-type: application/json

{
    "segments": [
        {"from": 1, "to": 2}
    ]
}
